### ISSUE TITLE
Modifier sizing classes output non-working code

### ISSUE THREAD

**Issue by vongoh** [inuitcss/objects.list-ui#7]
I'm integrating the new Inuit modules into my own framework, and I'm running into this same issue in any module that has code similar to this:

~~~
$inuit-list-ui-padding--tiny:     quarter($inuit-list-ui-padding) !default;
$inuit-list-ui-padding--small:      halve($inuit-list-ui-padding) !default;
$inuit-list-ui-padding--large:     double($inuit-list-ui-padding) !default;
$inuit-list-ui-padding--huge:   quadruple($inuit-list-ui-padding) !default;
~~~

When I hook this up to test it out on some markup,  then run it -- this outputs to CSS:

~~~
// For example (my module prefix alias is `o-`) ..
.o-list-ui__tiny {
      padding:  quarter(24px);
} 
~~~

Firefox apparently doesn't know what to do with this, because this class - and all of these sizing calculation classes, regardless of the module they are used in - is dead and does not apply.

To temporarily fix this - I have been copying the code from the bower install,  making a new partial in my framework,  and renaming all of the variables that are based on $inuit-base-spacing-unit with my own variable called $baseline.

I integrated this variable with Inuit inside `_inuit-settings.aliases.scss` like so:

~~~
// Reassign: Inuit base spacing unit, to $baseline
$baseline: $inuit-base-spacing-unit; 

~~~

Then in my own `_config.scss`  I have these:

~~~
// Baseline Variations ($baseline is defined in _inuit-settings.aliases.scss)
$baseline--qrtr     : $baseline / 4;
$baseline--half     : $baseline / 2;
$baseline--dble     : $baseline * 2;
$baseline--quad     : $baseline * 4;
~~~

... and when I apply these to the settings modifier classes in my new partial, the calculation outputs properly and they all work fine.

Needless to say I'm breaking the point of having a bower install by doing this, but at the moment I have projects coming up that I plan to use these modules in and I have to make it work.  I'm not up on whats happening here otherwise but I figured to give you guys the heads up ..

**Comment by csshugs** [comment]
But you do have the inuit [tools.functions](https://github.com/inuitcss/tools.functions) module integrated in your project?

**Comment by florianbouvot** [comment]
To use this `inuitcss` module you need at least this configuration :

1 - install via bower *(or npm, or manually)*
```
$ bower install --save inuit-list-ui
```

2 - import dependencies into your Sass project *(in the following order)*
```
@import "../bower_components/inuit-defaults/settings.defaults";
@import "../bower_components/inuit-functions/tools.functions";
@import "../bower_components/inuit-list-ui/objects.list-ui";
```

3 - configure the module in your Sass file to match your needs (optional)
```
$spacing:    20px;
@import "../bower_components/inuit-defaults/settings.defaults";
@import "../bower_components/inuit-functions/tools.functions";

// configuration sample
$inuit-list-ui-namespace:       o-;
$inuit-list-ui-padding:         $spacing;
$inuit-list-ui-padding--tiny:   quarter($spacing);
$inuit-list-ui-padding--small:  halve($spacing);
$inuit-list-ui-padding--large:  double($spacing);
$inuit-list-ui-padding--huge:   quadruple($spacing);

$inuit-list-ui-border-width:    2px;
$inuit-list-ui-border-style:    solid;
$inuit-list-ui-border-color:    #666;

$inuit-enable-list-ui--tiny:    true;
$inuit-enable-list-ui--small:   true;
$inuit-enable-list-ui--large:   true;
$inuit-enable-list-ui--huge:    true;
@import "../bower_components/inuit-list-ui/objects.list-ui";
```

**Comment by vongoh** [comment]
@csshugs yes, absolutely.

Its the return of the functions from that file that the brower does not understand:

~~~
padding:  quarter(24px);

~~~

This is what is coming out in my generated `global.css`.  That's what I'm wondering about.  Could be a grunt-sass bug? I havent pursued this with them, I'm just throwing that out there to see what you guys think.

**Comment by vongoh** [comment]
@florianbouvot  Yes, all of that is done.  See my response above..

**Comment by csshugs** [comment]
@fuhlig Seems like the same problem you once had. Did you manage to solve that problem ever since?

@vongoh Apart from that, I'm sure this is a Sass compile problem on your machine, but let's see what @fuhlig has to say.

**Comment by csshugs** [comment]
@vongoh 
The problem is that your Sass generator wont generate the content of the ["tools.function" file](https://github.com/inuitcss/tools.functions/blob/master/_tools.functions.scss).

What Sass version do you use? Did you try to update or use libsass instead? The problem must be something with your Sass generator. Maybe it's your Ruby version, so maybe have a try with libsass.

As I said above, @fuhlig had the exact same problem but didn't managed to solve the issue. Seems like very few people have a strange combination of Ruby version + node.js version + Sass version + Windows (?) + I don't know what. It's strange because what "tools.functions" does is actually not very much and quite "simple".

**Comment by vongoh** [comment]
I don't use Ruby anymore. I'm using grunt-sass ~1.1.0 .. so yes, whichever build of libsass that is drawing on is doing the compiling,  finding exactly which one is a labyrinthine process or maybe I just cant find the right link.

Yes that's what mystified me about the issue at first,  its not like `tools.functions` is doing anything crazy and radical ..
